site_name: DUSTY ROADS - A DUST Modding Guide & Wabbajack
site_url: https://tkrrptd.github.io/dusty-roads/

theme:
  name: material
  palette:
    scheme: slate
    primary: orange
    accent: orange
  favicon: 'images/tunneler.ico' 
  logo: 'images/tunneler.ico'
  font:
    text: Courier Prime
    code: Share Tech Mono
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
  custom_dir: docs/overrides    
    
extra_css:
  - css/custom.css

markdown_extensions:
  - attr_list

nav:
  - index.md
  - DUSTY ROADS - BASE |:
    - Introduction: guide.md
    - Preparation: preparation.md
    - Mod Organizer 2: mo2.md
    - Utilities: utilities.md
    - Bug Fixes: fixes.md
    - User Interface: ui.md
    - Gameplay: gameplay.md
    - DUST: dust.md
    - Choose your Road: crossroads.md
  - DUSTY ROADS - EXPANDED |:
    - expanded.md
    - User Interface: expanded-ui.md
    - Gameplay: expanded-gameplay.md    
    - Content: expanded-content.md
    - Audio: expanded-audio.md
    - Animations: expanded-animations.md
    - Visuals: expanded-visuals.md
    - DUST Mods: expanded-dust.md
    - DUST Patches: expanded-patches.md
  - END OF THE ROAD |:  
    - LOD Generation: lod.md
    - Finishing Touch: finish.md
    - Support & FAQ: support.md
  - ADDITIONAL MODS |:  
    - optional.md
    - User Interface: optional-ui.md
    - Gameplay: optional-gameplay.md
    - Content: optional-content.md
    - Audio: optional-audio.md
    - Animations: optional-animations.md
    - Visuals: optional-visuals.md
    - New Vegas Reloaded: optional-nvr.md
  - WABBAJACK |: wabbajack.md
  - RESOURCES |:  
    - Resources: resources.md
    - Support & FAQ: support.md
    - DUST Perk Planner: https://simonwdev.github.io/simonwdev/fnv/dust-planner/
  - CHANGELOG: changelog.md
